---
driver:
  name: lxd
  image_server: 'https://cloud-images.ubuntu.com/releases'
  username: ubuntu

provisioner: shell

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
    transport: lxd
    verifier:
      name: inspec
