---
driver:
  name: lxd

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
    transport: lxd
#    verifier:
#      name: inspec
  - name: travis
    run_list: travis::default
    driver:
      name: exec
