sudo: required
language: ruby
rvm:
- 2.5.1
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install:
- gem uninstall bundler || true
- gem install bundler -v 1.17.3
script:
- unset BUNDLE_GEMFILE
- KITCHEN_LOCAL_YAML=.kitchen.travis.yml kitchen converge travis
- sudo rm -rf ~/.config/lxc
- sudo su -l $USER -c "cd $(pwd) && rvm use ${RUBY_VERSION/ruby-/} && rake kitchen:all"
