sudo: required
language: ruby
rvm:
- 2.4.3
- 2.5.0
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
script:
- KITCHEN_LOCAL_YAML=.kitchen.travis.yml kitchen converge travis
- sudo rm -rf ~/.config/lxc
- sudo su -l $USER -c "cd $(pwd) && rvm use ${RUBY_VERSION/ruby-/} && kitchen test default"
